import { FC, ReactNode } from 'react';
import Head from 'next/head';

type Props = {
  title: string;
  children: ReactNode;
};

export const Layout: FC<Props> = ({
  children,
  title = 'Next.js Component Catalog',
}) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="m-0 mx-auto flex min-h-screen flex-col items-center justify-center bg-slate-200">
        {children}
      </main>
    </>
  );
};
